version: "3.9"
services:
  pptr-gpt-server:
    container_name: pprt-gpt-server
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - "3000:3000"
    privileged: true
